source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'activerecord', '~> 7.0'
gem 'mysql2', '~> 0.5'
gem 'standalone_migrations', '~> 7.0'
gem 'puma', '~> 6.0'
gem 'rake'
gem 'nokogiri', '~> 1.16'
gem 'builder', '~> 3.2'