development:
  adapter: mysql2
  host: db
  port: 3306
  username: root
  password: a
  database: instrumentos_development
  encoding: utf8mb4

production:
  adapter: mysql2
  host: db
  port: 3306
  username: root
  password: a
  database: instrumentos_production
  encoding: utf8mb4